In [ ]:
import pandas as pd

X_train = pd.read_csv("X_train.csv")
X_test = pd.read_csv("X_test.csv")
y_train = pd.read_csv("y_train.csv")
y_test = pd.read_csv("y_test.csv")

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

print("\nX_train:")
display(X_train.head())

print("\ny_train:")
display(y_train.head())

X_train shape: (492, 12)
X_test shape: (123, 12)
y_train shape: (492, 1)
y_test shape: (123, 1)

X_train:

,Age,ALB,ALP,ALT,AST,BIL,CHE,CHOL,CREA,GGT,PROT,Sex_m
0,-1.843528,1.279727,-0.070879,0.876087,0.130462,0.147888,0.286335,-1.557572,-0.050948,-0.043344,3.355551,1
1,0.197691,-0.391831,-0.376408,-0.393621,-0.587853,-0.326579,-0.061114,-0.686040,0.021830,-0.521971,0.444150,0
2,-1.435284,-0.167807,0.290625,-0.602190,-0.548944,-0.405657,-0.189122,0.896946,-0.269281,-0.385221,-0.093624,0
3,0.503874,7.000936,0.687114,0.290631,-0.327464,-0.187030,0.336624,0.656830,-0.087337,0.949075,-0.835383,1
4,-0.516735,-1.477482,0.537848,-0.927850,0.630290,8.753414,-2.945859,-0.170236,0.132815,2.091919,-0.371784,0

y_train:

        Category
0    1=Hepatitis
1  0=Blood Donor
2  0=Blood Donor
3  0=Blood Donor
4    3=Cirrhosis

In [ ]:
print("Training target classes:")
print(y_train["Category"].value_counts())

print("\nTest target classes:")
print(y_test["Category"].value_counts())

Training target classes:
Category
0=Blood Donor             426
3=Cirrhosis                24
1=Hepatitis                19
2=Fibrosis                 17
0s=suspect Blood Donor      6
Name: count, dtype: int64

Test target classes:
Category
0=Blood Donor             107
3=Cirrhosis                 6
1=Hepatitis                 5
2=Fibrosis                  4
0s=suspect Blood Donor      1
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder


y_train_series = y_train["Category"]
y_test_series = y_test["Category"]


label_encoder = LabelEncoder()

y_train_encoded = label_encoder.fit_transform(y_train_series)
y_test_encoded = label_encoder.transform(y_test_series)

# Show the mapping
print("Class mapping:")
for number, label in enumerate(label_encoder.classes_):
    print(number, "=", label)

print("\nEncoded training labels:")
print(y_train_encoded[:10])

print("\nEncoded test labels:")
print(y_test_encoded[:10])

Class mapping:
0 = 0=Blood Donor
1 = 0s=suspect Blood Donor
2 = 1=Hepatitis
3 = 2=Fibrosis
4 = 3=Cirrhosis

Encoded training labels:
[2 0 0 0 4 0 0 4 0 0]

Encoded test labels:
[0 0 0 0 0 0 0 0 0 0]

In [ ]:
from sklearn.linear_model import LogisticRegression

# Create the Logistic Regression model
logistic_model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=42
)

# Train the model
logistic_model.fit(X_train, y_train_encoded)

print("Logistic Regression trained successfully!")

Logistic Regression trained successfully!

In [ ]:
# Make predictions
y_pred_logistic = logistic_model.predict(X_test)

# Get prediction probabilities
y_prob_logistic = logistic_model.predict_proba(X_test)

print("Predictions:")
print(y_pred_logistic[:10])

print("\nProbability shape:", y_prob_logistic.shape)

Predictions:
[0 0 0 0 0 0 0 0 0 0]

Probability shape: (123, 5)

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

accuracy = accuracy_score(y_test_encoded, y_pred_logistic)
precision = precision_score(y_test_encoded, y_pred_logistic, average="weighted", zero_division=0)
recall = recall_score(y_test_encoded, y_pred_logistic, average="weighted", zero_division=0)
f1 = f1_score(y_test_encoded, y_pred_logistic, average="weighted", zero_division=0)

print("Logistic Regression Results")
print("----------------------------")
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

print("\nClassification Report:")
print(classification_report(
    y_test_encoded,
    y_pred_logistic,
    target_names=label_encoder.classes_,
    zero_division=0
))

print("Confusion Matrix:")
print(confusion_matrix(y_test_encoded, y_pred_logistic))

Logistic Regression Results
----------------------------
Accuracy : 0.926829268292683
Precision: 0.9436641370574593
Recall   : 0.926829268292683
F1 Score : 0.9323021152289445

Classification Report:
                        precision    recall  f1-score   support

         0=Blood Donor       0.99      0.95      0.97       107
0s=suspect Blood Donor       0.50      1.00      0.67         1
           1=Hepatitis       0.43      0.60      0.50         5
            2=Fibrosis       0.67      1.00      0.80         4
           3=Cirrhosis       0.80      0.67      0.73         6

              accuracy                           0.93       123
             macro avg       0.68      0.84      0.73       123
          weighted avg       0.94      0.93      0.93       123

Confusion Matrix:
[[102   0   4   0   1]
 [  0   1   0   0   0]
 [  1   0   3   1   0]
 [  0   0   0   4   0]
 [  0   1   0   1   4]]

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Create Random Forest model
random_forest_model = RandomForestClassifier(
    n_estimators=200,
    class_weight="balanced",
    random_state=42
)

# Train the model
random_forest_model.fit(X_train, y_train_encoded)

print("Random Forest trained successfully!")

Random Forest trained successfully!

In [ ]:
# Make Random Forest predictions
y_pred_rf = random_forest_model.predict(X_test)

# Get prediction probabilities
y_prob_rf = random_forest_model.predict_proba(X_test)

print("Random Forest predictions:")
print(y_pred_rf[:10])

print("\nProbability shape:", y_prob_rf.shape)

Random Forest predictions:
[0 0 0 0 0 0 0 0 0 0]

Probability shape: (123, 5)

In [ ]:
accuracy_rf = accuracy_score(y_test_encoded, y_pred_rf)
precision_rf = precision_score(
    y_test_encoded, y_pred_rf,
    average="weighted",
    zero_division=0
)
recall_rf = recall_score(
    y_test_encoded, y_pred_rf,
    average="weighted",
    zero_division=0
)
f1_rf = f1_score(
    y_test_encoded, y_pred_rf,
    average="weighted",
    zero_division=0
)

print("Random Forest Results")
print("---------------------")
print("Accuracy :", accuracy_rf)
print("Precision:", precision_rf)
print("Recall   :", recall_rf)
print("F1 Score :", f1_rf)

print("\nClassification Report:")
print(classification_report(
    y_test_encoded,
    y_pred_rf,
    target_names=label_encoder.classes_,
    zero_division=0
))

print("Confusion Matrix:")
print(confusion_matrix(y_test_encoded, y_pred_rf))

Random Forest Results
---------------------
Accuracy : 0.943089430894309
Precision: 0.9286786786786787
Recall   : 0.943089430894309
F1 Score : 0.9346945786865232

Classification Report:
                        precision    recall  f1-score   support

         0=Blood Donor       0.96      1.00      0.98       107
0s=suspect Blood Donor       0.00      0.00      0.00         1
           1=Hepatitis       0.75      0.60      0.67         5
            2=Fibrosis       0.33      0.25      0.29         4
           3=Cirrhosis       1.00      0.83      0.91         6

              accuracy                           0.94       123
             macro avg       0.61      0.54      0.57       123
          weighted avg       0.93      0.94      0.93       123

Confusion Matrix:
[[107   0   0   0   0]
 [  1   0   0   0   0]
 [  1   0   3   1   0]
 [  2   0   1   1   0]
 [  0   0   0   1   5]]

In [ ]:
# Install XGBoost if needed
!pip install -q xgboost

from xgboost import XGBClassifier

# Create XGBoost model
xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="multi:softprob",
    num_class=5,
    eval_metric="mlogloss",
    random_state=42
)

# Train the model
xgb_model.fit(X_train, y_train_encoded)

print("XGBoost trained successfully!")

XGBoost trained successfully!

In [ ]:
# Make XGBoost predictions
y_pred_xgb = xgb_model.predict(X_test)

# Get prediction probabilities
y_prob_xgb = xgb_model.predict_proba(X_test)

print("XGBoost predictions:")
print(y_pred_xgb[:10])

print("\nProbability shape:", y_prob_xgb.shape)

XGBoost predictions:
[0 0 0 0 0 0 0 0 0 0]

Probability shape: (123, 5)

In [ ]:
accuracy_xgb = accuracy_score(y_test_encoded, y_pred_xgb)

precision_xgb = precision_score(
    y_test_encoded,
    y_pred_xgb,
    average="weighted",
    zero_division=0
)

recall_xgb = recall_score(
    y_test_encoded,
    y_pred_xgb,
    average="weighted",
    zero_division=0
)

f1_xgb = f1_score(
    y_test_encoded,
    y_pred_xgb,
    average="weighted",
    zero_division=0
)

print("XGBoost Results")
print("----------------")
print("Accuracy :", accuracy_xgb)
print("Precision:", precision_xgb)
print("Recall   :", recall_xgb)
print("F1 Score :", f1_xgb)

print("\nClassification Report:")
print(classification_report(
    y_test_encoded,
    y_pred_xgb,
    target_names=label_encoder.classes_,
    zero_division=0
))

print("Confusion Matrix:")
print(confusion_matrix(y_test_encoded, y_pred_xgb))

XGBoost Results
----------------
Accuracy : 0.9512195121951219
Precision: 0.9433877825016783
Recall   : 0.9512195121951219
F1 Score : 0.9468602009252415

Classification Report:
                        precision    recall  f1-score   support

         0=Blood Donor       0.98      1.00      0.99       107
0s=suspect Blood Donor       0.00      0.00      0.00         1
           1=Hepatitis       0.60      0.60      0.60         5
            2=Fibrosis       0.50      0.50      0.50         4
           3=Cirrhosis       1.00      0.83      0.91         6

              accuracy                           0.95       123
             macro avg       0.62      0.59      0.60       123
          weighted avg       0.94      0.95      0.95       123

Confusion Matrix:
[[107   0   0   0   0]
 [  1   0   0   0   0]
 [  1   0   3   1   0]
 [  0   0   2   2   0]
 [  0   0   0   1   5]]

In [ ]:
import numpy as np
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)

def evaluate_model(y_true, y_pred, y_prob, model_name):

    # Basic metrics
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(
        y_true, y_pred,
        average="weighted",
        zero_division=0
    )
    recall = recall_score(
        y_true, y_pred,
        average="weighted",
        zero_division=0
    )
    f1 = f1_score(
        y_true, y_pred,
        average="weighted",
        zero_division=0
    )

    # Multiclass ROC-AUC
    roc_auc = roc_auc_score(
        y_true,
        y_prob,
        multi_class="ovr",
        average="weighted"
    )

    # Confusion matrix
    cm = confusion_matrix(y_true, y_pred)

    # Sensitivity and specificity for each class
    sensitivities = []
    specificities = []

    for i in range(len(cm)):
        tp = cm[i, i]
        fn = cm[i, :].sum() - tp
        fp = cm[:, i].sum() - tp
        tn = cm.sum() - (tp + fn + fp)

        sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0
        specificity = tn / (tn + fp) if (tn + fp) > 0 else 0

        sensitivities.append(sensitivity)
        specificities.append(specificity)

    # Macro average across classes
    sensitivity_macro = np.mean(sensitivities)
    specificity_macro = np.mean(specificities)

    return {
        "Model": model_name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "ROC-AUC": roc_auc,
        "Sensitivity": sensitivity_macro,
        "Specificity": specificity_macro
    }

In [ ]:
logistic_results = evaluate_model(
    y_test_encoded,
    y_pred_logistic,
    y_prob_logistic,
    "Logistic Regression"
)

rf_results = evaluate_model(
    y_test_encoded,
    y_pred_rf,
    y_prob_rf,
    "Random Forest"
)

xgb_results = evaluate_model(
    y_test_encoded,
    y_pred_xgb,
    y_prob_xgb,
    "XGBoost"
)

print(logistic_results)
print(rf_results)
print(xgb_results)

{'Model': 'Logistic Regression', 'Accuracy': 0.926829268292683, 'Precision': 0.9436641370574593, 'Recall': 0.926829268292683, 'F1': 0.9323021152289445, 'ROC-AUC': np.float64(0.9922394521756671), 'Sensitivity': np.float64(0.8439875389408099), 'Specificity': np.float64(0.974010248473539)}
{'Model': 'Random Forest', 'Accuracy': 0.943089430894309, 'Precision': 0.9286786786786787, 'Recall': 0.943089430894309, 'F1': 0.9346945786865232, 'ROC-AUC': np.float64(0.9954528618597387), 'Sensitivity': np.float64(0.5366666666666667), 'Specificity': np.float64(0.9449437402079475)}
{'Model': 'XGBoost', 'Accuracy': 0.9512195121951219, 'Precision': 0.9433877825016783, 'Recall': 0.9512195121951219, 'F1': 0.9468602009252415, 'ROC-AUC': np.float64(0.994812915997533), 'Sensitivity': np.float64(0.5866666666666667), 'Specificity': np.float64(0.9682488249537103)}

In [ ]:
import pandas as pd

# Combine all model results
results = pd.DataFrame([
    logistic_results,
    rf_results,
    xgb_results
])

# Display the comparison
display(results)

,Model,Accuracy,Precision,Recall,F1,ROC-AUC,Sensitivity,Specificity
0,Logistic Regression,0.926829,0.943664,0.926829,0.932302,0.992239,0.843988,0.974010
1,Random Forest,0.943089,0.928679,0.943089,0.934695,0.995453,0.536667,0.944944
2,XGBoost,0.951220,0.943388,0.951220,0.946860,0.994813,0.586667,0.968249

In [ ]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# Logistic Regression CV
logistic_cv = cross_val_score(
    logistic_model,
    X_train,
    y_train_encoded,
    cv=cv,
    scoring="f1_weighted"
)

# Random Forest CV
rf_cv = cross_val_score(
    random_forest_model,
    X_train,
    y_train_encoded,
    cv=cv,
    scoring="f1_weighted"
)

# XGBoost CV
xgb_cv = cross_val_score(
    xgb_model,
    X_train,
    y_train_encoded,
    cv=cv,
    scoring="f1_weighted"
)

print("5-Fold Cross-Validation (Weighted F1)")
print("--------------------------------------")

print("Logistic Regression:")
print("Scores:", logistic_cv)
print("Mean :", logistic_cv.mean())

print("\nRandom Forest:")
print("Scores:", rf_cv)
print("Mean :", rf_cv.mean())

print("\nXGBoost:")
print("Scores:", xgb_cv)
print("Mean :", xgb_cv.mean())

5-Fold Cross-Validation (Weighted F1)
--------------------------------------
Logistic Regression:
Scores: [0.93072498 0.8474884  0.87572665 0.8937901  0.86518465]
Mean : 0.8825829566459051

Random Forest:
Scores: [0.88119614 0.91276947 0.89074234 0.87887526 0.89697488]
Mean : 0.892111617000341

XGBoost:
Scores: [0.90041541 0.92660455 0.87544237 0.9307309  0.90899255]
Mean : 0.9084371552315537

In [ ]:
from sklearn.model_selection import GridSearchCV

logistic_param_grid = {
    "C": [0.01, 0.1, 1, 10, 100],
    "solver": ["lbfgs"],
    "class_weight": ["balanced"]
}

logistic_grid = GridSearchCV(
    LogisticRegression(max_iter=2000, random_state=42),
    logistic_param_grid,
    cv=cv,
    scoring="f1_weighted",
    n_jobs=-1
)

logistic_grid.fit(X_train, y_train_encoded)

print("Best Logistic Regression parameters:")
print(logistic_grid.best_params_)

print("\nBest CV Weighted F1:")
print(logistic_grid.best_score_)

Best Logistic Regression parameters:
{'C': 0.01, 'class_weight': 'balanced', 'solver': 'lbfgs'}

Best CV Weighted F1:
0.8985609958304609

In [ ]:
rf_param_grid = {
    "n_estimators": [100, 200, 300],
    "max_depth": [None, 5, 10, 20],
    "min_samples_split": [2, 5],
    "class_weight": ["balanced"]
}

rf_grid = GridSearchCV(
    RandomForestClassifier(random_state=42),
    rf_param_grid,
    cv=cv,
    scoring="f1_weighted",
    n_jobs=-1
)

rf_grid.fit(X_train, y_train_encoded)

print("Best Random Forest parameters:")
print(rf_grid.best_params_)

print("\nBest CV Weighted F1:")
print(rf_grid.best_score_)

Best Random Forest parameters:
{'class_weight': 'balanced', 'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 200}

Best CV Weighted F1:
0.9045481174927209

In [ ]:
xgb_param_grid = {
    "n_estimators": [100, 200, 300],
    "max_depth": [2, 3, 4, 5],
    "learning_rate": [0.03, 0.05, 0.1],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.8, 1.0]
}

xgb_grid = GridSearchCV(
    XGBClassifier(
        objective="multi:softprob",
        num_class=5,
        eval_metric="mlogloss",
        random_state=42
    ),
    xgb_param_grid,
    cv=cv,
    scoring="f1_weighted",
    n_jobs=-1
)

xgb_grid.fit(X_train, y_train_encoded)

print("Best XGBoost parameters:")
print(xgb_grid.best_params_)

print("\nBest CV Weighted F1:")
print(xgb_grid.best_score_)

Best XGBoost parameters:
{'colsample_bytree': 1.0, 'learning_rate': 0.1, 'max_depth': 4, 'n_estimators': 300, 'subsample': 0.8}

Best CV Weighted F1:
0.9191828047540819

In [ ]:
# Get the best tuned models
best_logistic = logistic_grid.best_estimator_
best_rf = rf_grid.best_estimator_
best_xgb = xgb_grid.best_estimator_

# Make predictions
y_pred_logistic_tuned = best_logistic.predict(X_test)
y_pred_rf_tuned = best_rf.predict(X_test)
y_pred_xgb_tuned = best_xgb.predict(X_test)

# Get probabilities
y_prob_logistic_tuned = best_logistic.predict_proba(X_test)
y_prob_rf_tuned = best_rf.predict_proba(X_test)
y_prob_xgb_tuned = best_xgb.predict_proba(X_test)

print("All tuned models evaluated on test data successfully!")

All tuned models evaluated on test data successfully!

In [ ]:
# Evaluate tuned models using our common evaluation function

logistic_tuned_results = evaluate_model(
    y_test_encoded,
    y_pred_logistic_tuned,
    y_prob_logistic_tuned,
    "Logistic Regression (Tuned)"
)

rf_tuned_results = evaluate_model(
    y_test_encoded,
    y_pred_rf_tuned,
    y_prob_rf_tuned,
    "Random Forest (Tuned)"
)

xgb_tuned_results = evaluate_model(
    y_test_encoded,
    y_pred_xgb_tuned,
    y_prob_xgb_tuned,
    "XGBoost (Tuned)"
)

# Create final comparison table
final_results = pd.DataFrame([
    logistic_tuned_results,
    rf_tuned_results,
    xgb_tuned_results
])

display(final_results)

,Model,Accuracy,Precision,Recall,F1,ROC-AUC,Sensitivity,Specificity
0,Logistic Regression (Tuned),0.934959,0.949901,0.934959,0.940090,0.984830,0.835857,0.975761
1,Random Forest (Tuned),0.934959,0.935772,0.934959,0.934631,0.975543,0.582928,0.964873
2,XGBoost (Tuned),0.951220,0.943388,0.951220,0.946860,0.993695,0.586667,0.968249

In [ ]:
# Save final tuned-model results
final_results.to_csv("classical_results.csv", index=False)

print("classical_results.csv created successfully!")

classical_results.csv created successfully!

In [ ]:
import os

print(os.path.exists("classical_results.csv"))

True

In [ ]:
%%writefile classical_models.py

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


def create_logistic_regression():
    return LogisticRegression(
        C=0.01,
        class_weight="balanced",
        solver="lbfgs",
        max_iter=2000,
        random_state=42
    )


def create_random_forest():
    return RandomForestClassifier(
        class_weight="balanced",
        random_state=42
    )


def create_xgboost():
    return XGBClassifier(
        objective="multi:softprob",
        num_class=5,
        eval_metric="mlogloss",
        random_state=42
    )


def train_models(X_train, y_train):
    models = {
        "Logistic Regression": create_logistic_regression(),
        "Random Forest": create_random_forest(),
        "XGBoost": create_xgboost()
    }

    for model in models.values():
        model.fit(X_train, y_train)

    return models

Writing classical_models.py

In [ ]:
print("Best Logistic:", logistic_grid.best_params_)
print("Best Random Forest:", rf_grid.best_params_)
print("Best XGBoost:", xgb_grid.best_params_)

Best Logistic: {'C': 0.01, 'class_weight': 'balanced', 'solver': 'lbfgs'}
Best Random Forest: {'class_weight': 'balanced', 'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 200}
Best XGBoost: {'colsample_bytree': 1.0, 'learning_rate': 0.1, 'max_depth': 4, 'n_estimators': 300, 'subsample': 0.8}

In [ ]:
print("Best Logistic Regression:", logistic_grid.best_params_)
print("Best Random Forest:", rf_grid.best_params_)
print("Best XGBoost:", xgb_grid.best_params_)

Best Logistic Regression: {'C': 0.01, 'class_weight': 'balanced', 'solver': 'lbfgs'}
Best Random Forest: {'class_weight': 'balanced', 'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 200}
Best XGBoost: {'colsample_bytree': 1.0, 'learning_rate': 0.1, 'max_depth': 4, 'n_estimators': 300, 'subsample': 0.8}

In [ ]:
print("LOGISTIC")
for k, v in logistic_grid.best_params_.items():
    print(k, "=", v)

print("\nRANDOM FOREST")
for k, v in rf_grid.best_params_.items():
    print(k, "=", v)

print("\nXGBOOST")
for k, v in xgb_grid.best_params_.items():
    print(k, "=", v)

LOGISTIC
C = 0.01
class_weight = balanced
solver = lbfgs

RANDOM FOREST
class_weight = balanced
max_depth = 5
min_samples_split = 2
n_estimators = 200

XGBOOST
colsample_bytree = 1.0
learning_rate = 0.1
max_depth = 4
n_estimators = 300
subsample = 0.8

In [ ]:
%%writefile classical_models.py

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


def create_logistic_regression():
    return LogisticRegression(
        C=0.01,
        class_weight="balanced",
        solver="lbfgs",
        max_iter=2000,
        random_state=42
    )


def create_random_forest():
    return RandomForestClassifier(
        n_estimators=200,
        max_depth=5,
        min_samples_split=2,
        class_weight="balanced",
        random_state=42
    )


def create_xgboost():
    return XGBClassifier(
        n_estimators=300,
        max_depth=4,
        learning_rate=0.1,
        subsample=0.8,
        colsample_bytree=1.0,
        objective="multi:softprob",
        num_class=5,
        eval_metric="mlogloss",
        random_state=42
    )


def train_models(X_train, y_train):
    models = {
        "Logistic Regression": create_logistic_regression(),
        "Random Forest": create_random_forest(),
        "XGBoost": create_xgboost()
    }

    for model in models.values():
        model.fit(X_train, y_train)

    return models

Overwriting classical_models.py

In [ ]:
%%writefile evaluation.py

import numpy as np

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)


def evaluate_model(y_true, y_pred, y_prob, model_name):
    """
    Evaluate a multiclass classification model.

    Returns:
        Dictionary containing Accuracy, Precision, Recall,
        F1, ROC-AUC, Sensitivity and Specificity.
    """

    # Basic metrics
    accuracy = accuracy_score(y_true, y_pred)

    precision = precision_score(
        y_true,
        y_pred,
        average="weighted",
        zero_division=0
    )

    recall = recall_score(
        y_true,
        y_pred,
        average="weighted",
        zero_division=0
    )

    f1 = f1_score(
        y_true,
        y_pred,
        average="weighted",
        zero_division=0
    )

    # Multiclass ROC-AUC
    roc_auc = roc_auc_score(
        y_true,
        y_prob,
        multi_class="ovr",
        average="weighted"
    )

    # Confusion matrix
    cm = confusion_matrix(y_true, y_pred)

    sensitivities = []
    specificities = []

    # Calculate sensitivity and specificity for each class
    for i in range(len(cm)):

        tp = cm[i, i]
        fn = cm[i, :].sum() - tp
        fp = cm[:, i].sum() - tp
        tn = cm.sum() - (tp + fn + fp)

        sensitivity = (
            tp / (tp + fn)
            if (tp + fn) > 0
            else 0
        )

        specificity = (
            tn / (tn + fp)
            if (tn + fp) > 0
            else 0
        )

        sensitivities.append(sensitivity)
        specificities.append(specificity)

    # Macro average across classes
    sensitivity_macro = np.mean(sensitivities)
    specificity_macro = np.mean(specificities)

    return {
        "Model": model_name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "ROC-AUC": roc_auc,
        "Sensitivity": sensitivity_macro,
        "Specificity": specificity_macro
    }

Writing evaluation.py

In [ ]:
import os

print("classical_models.py:", os.path.exists("classical_models.py"))
print("evaluation.py:", os.path.exists("evaluation.py"))
print("classical_results.csv:", os.path.exists("classical_results.csv"))

classical_models.py: True
evaluation.py: True
classical_results.csv: True

In [ ]:
import os

print(os.listdir())

['.config', 'X_test.csv', 'evaluation.py', 'y_test.csv', 'X_train.csv', 'y_train.csv', 'classical_models.py', 'classical_results.csv', 'sample_data']

In [ ]:
%%writefile evaluation.py

import numpy as np

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)


def evaluate_model(y_true, y_pred, y_prob, model_name):

    accuracy = accuracy_score(y_true, y_pred)

    precision = precision_score(
        y_true, y_pred,
        average="weighted",
        zero_division=0
    )

    recall = recall_score(
        y_true, y_pred,
        average="weighted",
        zero_division=0
    )

    f1 = f1_score(
        y_true, y_pred,
        average="weighted",
        zero_division=0
    )

    roc_auc = roc_auc_score(
        y_true,
        y_prob,
        multi_class="ovr",
        average="weighted"
    )

    cm = confusion_matrix(y_true, y_pred)

    sensitivities = []
    specificities = []

    for i in range(len(cm)):

        tp = cm[i, i]
        fn = cm[i, :].sum() - tp
        fp = cm[:, i].sum() - tp
        tn = cm.sum() - (tp + fn + fp)

        sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0
        specificity = tn / (tn + fp) if (tn + fp) > 0 else 0

        sensitivities.append(sensitivity)
        specificities.append(specificity)

    return {
        "Model": model_name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "ROC-AUC": roc_auc,
        "Sensitivity": np.mean(sensitivities),
        "Specificity": np.mean(specificities)
    }

Overwriting evaluation.py